# DATASOURCE
RMDB_URL: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
RMDB_USERNAME: root
RMDB_PASSWORD: '111111'
RMDB_MAX_POOL_SIZE: 100
RMDB_MINI_IDLE: 10
RMDB_IDLE_TIMEOUT: 600000
RMDB_CONNECTION_TIMEOUT: 600000
RMDB_MAX_LIFE_TIME: 600000
RMDB_VALIDATION_TIME: 5000